import { createHash } from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import path from "node:path";
import type { GauntletProgressSnapshot } from "./types";
import type { PublishedProgressBundle, PublishedSnapshotEntry } from "./published-progress";

const SAFE_COMPONENT = /^[a-z0-9][a-z0-9_-]*$/;

function sha256(value: string) {
  return createHash("sha256").update(value).digest("hex");
}

async function atomicWrite(filePath: string, content: string) {
  const temporaryPath = `${filePath}.tmp-${process.pid}`;
  await writeFile(temporaryPath, content, "utf8");
  await rename(temporaryPath, filePath);
}

export async function publishGauntletProgressSnapshot(
  snapshot: GauntletProgressSnapshot,
  explicitWebRoot?: string,
) {
  if (!SAFE_COMPONENT.test(snapshot.iteration.id)
    || !SAFE_COMPONENT.test(snapshot.manifest.activeIterationId)) {
    throw new Error("Published Gauntlet iteration IDs must be safe path components");
  }
  const publishedRoot = path.join(path.resolve(explicitWebRoot ?? process.cwd()), "gauntlet", "published");
  const bundlePath = path.join(publishedRoot, "progress.json");
  const modulePath = path.join(publishedRoot, "progress-data.ts");
  await mkdir(publishedRoot, { recursive: true });

  let existing: PublishedProgressBundle | null = null;
  try {
    existing = JSON.parse(await readFile(bundlePath, "utf8")) as PublishedProgressBundle;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
  const entry: PublishedSnapshotEntry = {
    iterationId: snapshot.iteration.id,
    sha256: sha256(JSON.stringify(snapshot)),
    snapshot,
  };
  const snapshots = (existing?.snapshots ?? [])
    .filter((candidate) => candidate.iterationId !== snapshot.iteration.id)
    .concat(entry)
    .sort((left, right) => left.iterationId.localeCompare(right.iterationId));
  const bundle: PublishedProgressBundle = {
    schemaVersion: "1",
    activeIterationId: snapshot.manifest.activeIterationId,
    snapshots,
  };
  if (!snapshots.some((candidate) => candidate.iterationId === bundle.activeIterationId)) {
    throw new Error(`Publish the active Gauntlet iteration before ${snapshot.iteration.id}`);
  }
  const serialized = JSON.stringify(bundle, null, 2);
  await atomicWrite(bundlePath, `${serialized}\n`);
  await atomicWrite(
    modulePath,
    `// Generated by npm run gauntlet:publish. Do not edit by hand.\nexport const publishedProgressBundle = ${serialized} as const;\n`,
  );
  return { publishedRoot, entry };
}
