export const GAUNTLET_VALIDATOR_PATH = "web/lib/backend/validation.ts";
export const GAUNTLET_FINALIZER_PATH = "web/scripts/gauntlet-report-finalizer.ts";
export const GAUNTLET_AUTOMATED_CHECK_PATHS = Object.freeze([
  "web/lib/evals/checks.ts",
  "web/lib/evals/types.ts",
  "web/lib/llm/grounding.ts",
  "tests/fixtures/calibration.json",
] as const);

export const GAUNTLET_RUNTIME_CLOSURE_PATHS = Object.freeze([
  "web/package.json",
  "web/package-lock.json",
  "web/next.config.mjs",
  "web/prompts/resume_v2.txt",
  "web/scripts/run-ts-script.cjs",
  "web/scripts/run-gauntlet.ts",
  "web/scripts/run-gauntlet-eval.ts",
  "web/scripts/run-eval.ts",
  "web/scripts/gauntlet-evidence-capture.ts",
  "web/scripts/gauntlet-evidence-capture/browser.ts",
  "web/scripts/gauntlet-evidence-capture/browser-artifacts.ts",
  "web/scripts/gauntlet-evidence-capture/browser-identity.ts",
  "web/scripts/gauntlet-evidence-capture/browser-page.ts",
  "web/scripts/gauntlet-evidence-capture/browser-runner.ts",
  "web/scripts/gauntlet-evidence-capture/capture-paths.ts",
  "web/scripts/gauntlet-evidence-capture/contracts.ts",
  "web/scripts/gauntlet-evidence-capture/network-guard.cjs",
  "web/scripts/gauntlet-evidence-capture/repository.ts",
  "web/scripts/gauntlet-evidence-capture/repository-dependencies.ts",
  "web/scripts/gauntlet-evidence-capture/repository-git.ts",
  "web/scripts/gauntlet-evidence-capture/repository-plan.ts",
  "web/scripts/gauntlet-evidence-capture/repository-runtime.ts",
  "web/scripts/gauntlet-evidence-capture/runner-attestation.ts",
  "web/lib/gauntlet/dependency-closure.ts",
  "web/lib/gauntlet/integrity.ts",
  "web/lib/gauntlet/packets.ts",
  "web/lib/gauntlet/progress.ts",
  "web/lib/gauntlet/progress/anchors.ts",
  "web/lib/gauntlet/progress/api.ts",
  "web/lib/gauntlet/progress/automated.ts",
  "web/lib/gauntlet/progress/common.ts",
  "web/lib/gauntlet/progress/critic.ts",
  "web/lib/gauntlet/progress/definition.ts",
  "web/lib/gauntlet/progress/evidence.ts",
  "web/lib/gauntlet/progress/generation.ts",
  "web/lib/gauntlet/progress/inventory.ts",
  "web/lib/gauntlet/progress/outputs.ts",
  "web/lib/gauntlet/progress/reviews.ts",
  "web/lib/gauntlet/progress/summary.ts",
  "web/lib/gauntlet/runtime-paths.ts",
  "web/lib/gauntlet/reference-contract.ts",
  "web/lib/gauntlet/types.ts",
  "web/lib/evals/runner.ts",
  ...GAUNTLET_AUTOMATED_CHECK_PATHS,
  "web/lib/llm/evidence-canonicalizer.ts",
  "web/lib/llm/resume-score-calibration.ts",
  "web/lib/backend/errors.ts",
  GAUNTLET_VALIDATOR_PATH,
  "web/lib/validation/schemas.ts",
  "web/lib/score-utils.ts",
  "web/components/workspace/WorkspaceClient.tsx",
  "web/components/workspace/ResumeModeSection.tsx",
  "web/components/workspace/ReportPanel.tsx",
  "web/components/workspace/report/ReportStream.tsx",
  GAUNTLET_FINALIZER_PATH,
] as const);
