export const CAPTURE_HARNESS_PATHS = Object.freeze([
  "web/package.json",
  "web/lib/gauntlet/dependency-closure.ts",
  "web/lib/gauntlet/runtime-paths.ts",
  "web/lib/gauntlet/types.ts",
  "web/scripts/run-ts-script.cjs",
  "web/scripts/run-gauntlet-eval.ts",
  "web/scripts/run-eval.ts",
  "web/scripts/gauntlet-evidence-capture.ts",
  "web/scripts/gauntlet-evidence-capture/browser.ts",
  "web/scripts/gauntlet-evidence-capture/browser-artifacts.ts",
  "web/scripts/gauntlet-evidence-capture/browser-identity.ts",
  "web/scripts/gauntlet-evidence-capture/browser-page.ts",
  "web/scripts/gauntlet-evidence-capture/browser-runner.ts",
  "web/scripts/gauntlet-evidence-capture/capture-paths.ts",
  "web/scripts/gauntlet-evidence-capture/contracts.ts",
  "web/scripts/gauntlet-evidence-capture/network-guard.cjs",
  "web/scripts/gauntlet-evidence-capture/repository.ts",
  "web/scripts/gauntlet-evidence-capture/repository-dependencies.ts",
  "web/scripts/gauntlet-evidence-capture/repository-git.ts",
  "web/scripts/gauntlet-evidence-capture/repository-plan.ts",
  "web/scripts/gauntlet-evidence-capture/repository-runtime.ts",
  "web/scripts/gauntlet-evidence-capture/runner-attestation.ts",
  "web/lib/evals/runner.ts",
] as const);
