"use client";

import { Download, FilePlus } from "lucide-react";
import AnalysisScanning from "./AnalysisScanning";
import { ReportStream } from "./report/ReportStream";
import { ReportData } from "./report/ReportTypes";

// Re-export specific props if needed, but mainly we ingest ReportData
interface ReportPanelProps {
    report: ReportData | null;
    isLoading: boolean;
    hasJobDescription: boolean;
    onExportPdf?: () => void;
    isExporting?: boolean;
    isSample?: boolean;
}

export default function ReportPanel({
    report,
    isLoading,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    hasJobDescription,
    onExportPdf,
    isExporting = false,
    isSample = false
}: ReportPanelProps) {

    // Derived states
    const showEmptyState = !report && !isLoading;
    const showReport = !!report;

    return (
        <div className="flex flex-col h-full overflow-y-auto bg-body relative group">

            {/* BACKGROUND NOISE/TEXTURE (Subtle Studio Feel) */}
            <div className="absolute inset-0 bg-[url('/assets/noise.png')] opacity-[0.015] pointer-events-none mix-blend-overlay" />

            {/* 3. The Report Stream */}
            {showReport && (
                <div className="flex justify-center p-6 md:p-12 lg:py-16 bg-muted/10 min-h-full">
                    <div className="w-full max-w-4xl space-y-6">

                        {/* Document Meta / Actions Header */}
                        <div className="flex items-center justify-between px-2 animate-in fade-in slide-in-from-bottom-2 duration-500">
                            <div className="space-y-1">
                                <div className="flex items-center gap-3">
                                    <h1 className="text-2xl font-serif font-semibold text-foreground tracking-tight">
                                        {report.job_alignment?.role_fit?.best_fit_roles?.[0] || 'Resume Audit'}
                                    </h1>
                                    {isSample && (
                                        <span className="text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full bg-amber-500/10 text-amber-600 border border-amber-500/20">
                                            Sample
                                        </span>
                                    )}
                                </div>
                                <p className="text-sm text-muted-foreground">Generated by Recruiter in Your Pocket</p>
                            </div>

                            {onExportPdf && (
                                <button
                                    onClick={onExportPdf}
                                    disabled={isExporting}
                                    className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium bg-white dark:bg-card border border-border shadow-sm hover:bg-muted/50 transition-colors disabled:opacity-50 text-foreground"
                                >
                                    <Download className="w-4 h-4" />
                                    <span>{isExporting ? "Exporting..." : "Download PDF"}</span>
                                </button>
                            )}
                        </div>

                        {/* The "Paper" */}
                        <div className="bg-background border border-border/50 shadow-sm rounded-xl p-8 md:p-12">
                            <ReportStream report={report} />
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
